**NUMPY TUTORIAL** By Shivank Gautam

Now we see that how Numpy works. i advise you people to follow the codes on screen at the same time while reading this Notebook.

In [2]:
import numpy as np     # import numpy package

if you get error like 'numpy not found' 
download it by **pip install numpy** from command line

In [6]:
k = [1,2,3]   # this is just a list.
print(type(k))


n = np.array([3,6,8]) # this is now we have created a numpy array
print(type(n))


<class 'list'>
<class 'numpy.ndarray'>


The numpy array are also mutable and elements in this are also accesed like list elements

In [9]:
n[2] = 90   # changed the third element of our numpy array
print(n)

[ 3  6 90]


Now lets see how to create a rank two or 2D array in numpy 

In [12]:
tn = [[2,3,5], [43,22,11]] # a 2D list

ntn = np.array([[54,212,5], [4332,222,21]])  #2D numpy array

In [15]:
print('--- List ---')
print(tn)
print('--- Numpy Array ---')
print(ntn)

--- List ---
[[2, 3, 5], [43, 22, 11]]
--- Numpy Array ---
[[  54  212    5]
 [4332  222   21]]


The NumPy array can be accesed by list method a the same time its own method lets see how ... ?

In [23]:
print(ntn[0][0])   # The List Method

print(ntn[0,0])    # The Numpy Method first '0' is indicating the row number and second one is denoting column
print(ntn[1,2])    # accessing the last element in our 2D numpy matri

54
54
21


In [24]:
ntn[1,2] = 69     # mutability property
print(ntn)

[[  54  212    5]
 [4332  222   69]]


Now we see slicing this property is important

In [25]:
print(ntn[0,:])  # doing this will print '0' row and all column

[ 54 212   5]


In [26]:
print(ntn[:,2]) # this will print all row of 2nd column

[ 5 69]


In [27]:
# Exercise_Here

In [28]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [33]:
b = np.array([1,2,0,1])

Now we will we see that how we can do more function on numpy array

In [34]:
print(a[np.arange(4), b])

[ 2  6  7 11]


In [42]:
a[np.arange(4), b] += 10000

In [43]:
a

array([[    1, 30002,     3],
       [    4,     5, 30006],
       [30007,     8,     9],
       [   10, 30011,    12]])

In [51]:
check_great = (a > 1)

In [52]:
check_great

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [53]:
print(a[check_great])

[30002     3     4     5 30006 30007     8     9    10 30011    12]


Now we see about datatypes

In [63]:
x = np.array([[3, 2],[2,2]])
print(x.dtype)

int64


In [66]:
y = np.array([[1.0,2.1],[2,2]], dtype=np.int64)

In [67]:
print(y.dtype)

int64


In [68]:
print(y)

[[1 2]
 [2 2]]


    Now we see The simplpe mathematical function.

In [88]:
a = np.array([[2,2],[1,3]])
b = np.array([[1,2],[2,4]])
print('a === \n', a)
print('b ===\n', b)

a === 
 [[2 2]
 [1 3]]
b ===
 [[1 2]
 [2 4]]


In [89]:
print(np.add(a,b))
print('--------------')
print(np.multiply(a,b))

[[3 4]
 [3 7]]
--------------
[[ 2  4]
 [ 2 12]]


** The Matrix multiplication **

In [92]:
print(np.dot(a,b))

[[ 6 12]
 [ 7 14]]


In [94]:
print(b.dot(a))

[[ 4  8]
 [ 8 16]]


In [96]:
c = np.array([[1,2],[2,3],[3,4]])

In [97]:
c.T

array([[1, 2, 3],
       [2, 3, 4]])

In [98]:
c.shape

(3, 2)

In [99]:
c

array([[1, 2],
       [2, 3],
       [3, 4]])

<h1>Broadcasting</h1>

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:



In [101]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
n = np.array([1,2,1])

q = np.empty_like(m)

In [103]:
q

array([[140599927237624,        25545456,               0],
       [              0,               0,               0],
       [             64,              80,        25545520]])

In [116]:
b = np.tile(n,(3,1))

In [117]:
b

array([[1, 2, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [118]:
q = m+b

In [114]:
q

array([[ 2,  4,  4],
       [ 5,  7,  7],
       [ 8, 10, 10]])

In [119]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v

In [120]:
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

<h1>Application Of BroadCasting</h1>

In [126]:
i = np.array([1,3,2])
p = np.array([2,3])


print(np.reshape(i,(3,1))*p)


[[2 3]
 [6 9]
 [4 6]]


array([1, 3, 2])

In [128]:
x = np.array([[1,2,3], [4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [125]:
print(x+i)

[[2 5 5]
 [5 8 8]]
